---
title: "SLEDS"
author: "Tom Nehil"
date: "December 15, 2014"
output: html_document
---
```{r}
library(reshape)
```


```{r}
sleds <- read.csv("../build/2014-sleds.csv", stringsAsFactors = TRUE)

#introduce NAs for less than ten schools so we can ignore them
sleds$grads <- as.numeric(as.character(sleds$grads))
sleds$college <- as.numeric(as.character(sleds$college))
sleds$remedial <- as.numeric(as.character(sleds$remedial))

#percent of grads and college enrollees needing developmental ed
sleds$pct.remedial.grads <- round(sleds$remedial / sleds$grads,2)
sleds$pct.remedial.enrollees <- round(sleds$remedial / sleds$college,2)
```

##Twin Cities high schools
```{r}
tcschools <- c(  "0001-03-352", #edison
                 "0001-03-354", #henry
                 "0001-03-358", #north
                 "0001-03-360", #roosevelt
                 "0001-03-362", #south
                 "0001-03-364", #southwest
                 "0001-03-368", #washburn
                 #"0625-01-240", cutting arlington since it closed
                 "0625-01-210", #central
                 "0625-01-212", #como park
                 "0625-01-215", #harding
                 "0625-01-220", #highland park
                 "0625-01-230") #johnson

tcgrads <- subset(sleds, id %in% tcschools)

#reshape to give yearly rates
tcgrads.byyear <- cast(tcgrads, id ~ year)

#calculate mean for each school
tcgrads.byyear$mean <- rowMeans(tcgrads.byyear, na.rm=TRUE)
tcgrads.byyear$mean <- round(tcgrads.byyear$mean, 2)
```

##Graduation rates
```{r}
graddata <- read.csv("../build/2012-grad-data.csv", stringsAsFactors = FALSE)

createid <- function(dist, type, school) {
  #district
  a <- ifelse(nchar(dist) < 4, paste(paste(replicate(4-nchar(dist), "0"), collapse=""), dist, sep=""), dist)

  #district type
  b <- ifelse(nchar(type) < 2, paste(paste(replicate(2-nchar(type), "0"), collapse=""), type, sep=""), type)

  #school
  c <- ifelse(nchar(school) < 3, paste(paste(replicate(3-nchar(school), "0"), collapse=""), school, sep=""), school)

  result = paste(a, b, c, sep = "-", collapse = "")
  return(result)
}

#Apply createid function to each row (combines three fields to match ids in SLEDS)
graddata$id <- apply(graddata[,c('District.Number','District.Type','School.Number')], 1, function(y) createid(y['District.Number'],y['District.Type'],y['School.Number']))

```

##Graduation Rates — Twin Cities
Add graduation rate data for Twin Cities schools to the data frame about remediation rates from above.
```{r}
#filter down to TC schools
tc.graddata <- subset(graddata, id %in% tcschools & Demographic.Group == "All Students" & Ending.Status == "Graduate")[c('id','Four..Year.Percent','School.Name')]

#rename Grad rate column to be more clear in merged data
tc.graddata <- rename(tc.graddata, c('Four..Year.Percent' = 'grad.rate'))

#format grad.rate to match rates in rest of data
tc.graddata$grad.rate <- round(tc.graddata$grad.rate/100,2)

#add grad data to byyear data frame
tcgrads.byyear <- merge(tc.graddata,tcgrads.byyear, key="id", all.x=T, sort=F)

#reorder columns
tcgrads.byyear <- tcgrads.byyear[,c('id','School.Name','2006','2007','2008','2009','2010','2011','2012','mean','grad.rate')]
```

##Statewide grads of large-ish high schools
```{r}
#High schools graduating 100 or more students
biggrads <- subset(sleds, grads > 99)

#reshape to give yearly rates
biggrads.byyear <- cast(biggrads, id ~ year)

#calculate mean for each school
biggrads.byyear$mean <- rowMeans(tcgrads.byyear, na.rm=TRUE)
biggrads.byyear$mean <- round(tcgrads.byyear$mean, 2)
```

##Add graduation rates to statewide big school data
```{r}

#filter down to big schools
biggrads.graddata <- subset(graddata, id %in% biggrads$id & Demographic.Group == "All Students" & Ending.Status == "Graduate")[c('id','Four..Year.Percent','School.Name')]

#rename Grad rate column to be more clear in merged data
biggrads.graddata <- rename(biggrads.graddata, c('Four..Year.Percent' = 'grad.rate'))

#format grad.rate to match rates in rest of data
biggrads.graddata$grad.rate <- round(biggrads.graddata$grad.rate/100,2)

#add grad data to byyear data frame
biggrads.byyear <- merge(biggrads.graddata,biggrads.byyear, key="id", all.x=T, sort=F)

#reorder columns
biggrads.byyear <- biggrads.byyear[,c('id','School.Name','2006','2007','2008','2009','2010','2011','2012','mean','grad.rate')]

```


##Export
Save results to CSV for visualization.
```{r}
write.csv(tcgrads.byyear, file="../build/school-remedial-and-grad-rates.csv", na='', row.names=F)
```

